# Generated by Django 2.2.16 on 2022-09-02 18:07

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220902_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(null=True, validators=[reviews.validators.validate_year], verbose_name='Год'),
        ),
    ]
